spring:

  freemarker:
    #是否检查模板位置是否存在
    check-template-location: true
    #req
    request-context-attribute: request
    # 设定模板的后缀
    suffix: .html
    content-type: text/html
    #是否启用freemarker
    enabled: true
    cache: false
    # 设定模板的加载路径，多个以逗号分隔，默认:
    template-loader-path: classpath:/templates
    charset: UTF-8
    settings:
      number_format: '0.##'

  mail:
    port: 465
    host: smtp.qiye.aliyun.com
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.qiye.aliyun.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true

  devtools:
    restart:
      enabled: true